export const AmbassdorsEng = [
    {
      name: "Mian Ziauddin",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/ziauddin.jpg", 
      from: "May 1952",
      to: "July 1953",
    },
    {
      name: "Dr. Omar Hayat Malik",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/umerMalik.jpg", 
      from: "January 1955",
      to: "April 1959",
    },
    {
      name: "Mr. Mohammad Ali",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/mAli.jpg",
      from: "April 1959",
      to: "March 1962",
    },
    {
      name: "Lt. Gen. K.M. Shaikh",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/kmSheikh.jpg", 
      from: "July 1962",
      to: "June 1966",
    },
    {
      name: "Mr. S. Maqbool Murshed",
      designation: "H.E. Ambassador",
      image: "/assets/img/others/about_me.png", 
      from: "June 1966",
      to: "April 1970",
    },
    {
      name: "Mr. S. Motahir Hussain",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/motahir.jpg", 
      from: "September 1970",
      to: "September 1973",
    },
    {
      name: "Mr. S. M. Khan",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/smKhan.jpg", 
      from: "January 1974",
      to: "April 1976",
    },
    {
      name: "Mr. Jamshed K.A. Marker",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/jamshed.jpg", 
      from: "August 1976",
      to: "October 1978",
    },
    {
      name: "Mr. Qamarul Islam",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/qamar.jpg",
      from: "January 1979",
      to: "December 1984",
    },
    {
      name: "Mr. Najmul Saqib Khan",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/najmul.jpg", 
      from: "August 1988",
      to: "July 1993",
    },
    {
      name: "Mr. Mujahid Hussain",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/mujahid.jpg", 
      from: "May 1994",
      to: "1998",
    },
    {
      name: "Mr. Touqir Hussain",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/toqer.jpg", 
      from: "June 1998",
      to: "January 2003",
    },
    {
      name: "Mr. Kamran Niaz",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/kamran.jpg", 
      from: "March 2003",
      to: "September 2008",
    },
    {
      name: "Mr. Noor Muhammad Jadmani",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/jadmani.jpg", 
      from: "January 26th 2009",
      to: "November 30, 2012",
    },
    {
      name: "Mr. Farukh Amil",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/amil.jpg", 
      from: "10 December 2012",
      to: "April 13, 2017",
    },
    {
      name: "Mr. Asad Majeed Khan",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/asadMajeed.jpg", 
      from: "15 July 2017",
      to: "February 03, 2019",
    },
    {
      name: "Mr. Imtiaz Ahmad",
      designation: "H.E. Ambassador",
      image: "/assets/img/keyPerson/imtiaz.jpg", 
      from: "22 July 2019",
      to: "March 28, 2022",
    },
  ];
  