export const AmbassdorsJpn = [
    {
      name: "ミアン・ジアウッディン",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/ziauddin.jpg", 
      from: "1952年5月",
      to: "1953年7月",
    },
    {
      name: "ドクター・オマール・ハヤット・マリク",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/umerMalik.jpg", 
      from: "1955年1月",
      to: "1959年4月",
    },
    {
      name: "モハンマド・アリ",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/mAli.jpg",
      from: "1959年4月",
      to: "1962年3月",
    },
    {
      name: "リト・ジェネラル・K.M. シェイク",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/kmSheikh.jpg", 
      from: "1962年7月",
      to: "1966年6月",
    },
    {
      name: "S. マクブル・ムルシェッド",
      designation: "H.E. 大使",
      image: "/assets/img/others/about_me.png", 
      from: "1966年6月",
      to: "1970年4月",
    },
    {
      name: "S. モタヒール・フセイン",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/motahir.jpg", 
      from: "1970年9月",
      to: "1973年9月",
    },
    {
      name: "S. M. カーン",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/smKhan.jpg", 
      from: "1974年1月",
      to: "1976年4月",
    },
    {
      name: "ジャムシェッド・K.A. マーカー",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/jamshed.jpg", 
      from: "1976年8月",
      to: "1978年10月",
    },
    {
      name: "カマルール・イスラム",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/qamar.jpg",
      from: "1979年1月",
      to: "1984年12月",
    },
    {
      name: "ナジュムル・サキブ・カーン",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/najmul.jpg", 
      from: "1988年8月",
      to: "1993年7月",
    },
    {
      name: "ムジャヒド・フセイン",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/mujahid.jpg", 
      from: "1994年5月",
      to: "1998年",
    },
    {
      name: "トゥキール・フセイン",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/toqer.jpg", 
      from: "1998年6月",
      to: "2003年1月",
    },
    {
      name: "カムラン・ニアズ",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/kamran.jpg", 
      from: "2003年3月",
      to: "2008年9月",
    },
    {
      name: "ノール・ムハンマド・ジャドマニ",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/jadmani.jpg", 
      from: "2009年1月26日",
      to: "2012年11月30日",
    },
    {
      name: "ファルーク・アミル",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/amil.jpg", 
      from: "2012年12月10日",
      to: "2017年4月13日",
    },
    {
      name: "アサド・マジード・カーン",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/asadMajeed.jpg", 
      from: "2017年7月15日",
      to: "2019年2月3日",
    },
    {
      name: "イムティアズ・アフマド",
      designation: "H.E. 大使",
      image: "/assets/img/keyPerson/imtiaz.jpg", 
      from: "2019年7月22日",
      to: "2022年3月28日",
    },
];
