export const peopleEng = [
    {
      name: "Raza Bashir Tarar",
      designation: "H.E. Ambassador",
      tel :  " (03)-5421-7741 (Ext. #21 & #31)",
      fax : "(03)-5421-3610(03)-5421-3610",
      image: "/assets/img/keyPerson/tarar.JPG",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "Ismat Hassan Sial",
      designation: "Deputy Chief of Mission",
      tel :  "(03)-5421-7741 (Ext. #21 & #31)",
      fax : "(03)-5421-3610",
      image: "/assets/img/keyPerson/ismah.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "Taimur Zulfiqar",
      designation: "Counsellor / Head of Chancery",
      tel :  "(03)-5421-7741 (Ext. #43)",
      fax : " (03)-5421-3610",
      image: "/assets/img/keyPerson/taimur.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "Chaudhary Talha Bin Khalid",
      designation: "First Secretary",
      tel :  "(03)-5421-3603",
      fax : "03)-5421-3610",
      image: "/assets/img/keyPerson/chsaab.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "Syed Irfan Abbas Shah",
      designation: "Minister (Economic)",
      tel :  "(03)-5421-7741 (Ext. #49 & 39)",
      fax : "(03)-3445-6816",
      image: "/assets/img/keyPerson/irfan.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "Air Commodore. Yasir Shafiq Malik",
      designation: "Defence Attache",
      tel :  "(03)-5421-7741 (Ext. #45 & 35)",
      fax : "(03)-5421-3611",
      image: "/assets/img/others/about_me.png",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "Muqarrab Mukhtar Awan",
      designation: "Press Counsellor",
      tel :  "(03)-5421-7741 (Ext. #47 & 37)",
      fax : "(03)-5421-3612",
      image: "/assets/img/keyPerson/muqarab.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "Madiha Ali",
      designation: "Trade & Investment Counsellor",
      tel :  "(03)-5421-7741 (Ext. #46 & #36))",
      fax : "(03)-5421-3613",
      image: "/assets/img/others/about_me.png",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "Aashij Luqman Hafiz",
      designation: "Community Welfare Attache",
      tel :  "(03)-5421-7741 (Ext. #21 & #31)",
      fax : "(03)-5421-3610",
      image: "/assets/img/keyPerson/ashij.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "Muhammad Naveed Shahzad",
      designation: "Incharge  Machine Readable Passport",
      tel :  "(03)-5421-7742 (Ext. #13)",
      fax : " (03)-5421-3610",
      image: "/assets/img/keyPerson/naveed.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },

  ];