export const peopleJpn = [
    {
      name: "ラザ・バシール・タラー",
      designation: "大使",
      tel: "(03)-5421-7741 (内線 #21 & #31)",
      fax: "(03)-5421-3610(03)-5421-3610",
      image: "/assets/img/keyPerson/tarar.JPG",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "イスマット・ハッサン・シアル",
      designation: "副大使",
      tel: "(03)-5421-7741 (内線 #21 & #31)",
      fax: "(03)-5421-3610",
      image: "/assets/img/keyPerson/ismah.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "タイムール・ズルフィカール",
      designation: "参事官／庶務課長",
      tel: "(03)-5421-7741 (内線 #43)",
      fax: "(03)-5421-3610",
      image: "/assets/img/keyPerson/taimur.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "チャウダリー・タルハ・ビン・カリド",
      designation: "一等書記官",
      tel: "(03)-5421-3603",
      fax: "03)-5421-3610",
      image: "/assets/img/keyPerson/chsaab.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "サイード・イルファン・アッバス・シャー",
      designation: "経済担当大臣",
      tel: "(03)-5421-7741 (内線 #49 & 39)",
      fax: "(03)-3445-6816",
      image: "/assets/img/keyPerson/irfan.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "エアコモドール・ヤシル・シャフィーク・マリク",
      designation: "防衛駐在官",
      tel: "(03)-5421-7741 (内線 #45 & 35)",
      fax: "(03)-5421-3611",
      image: "/assets/img/others/about_me.png",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "ムカラブ・ムクタル・アワン",
      designation: "広報参事官",
      tel: "(03)-5421-7741 (内線 #47 & 37)",
      fax: "(03)-5421-3612",
      image: "/assets/img/keyPerson/muqarab.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "マディハ・アリ",
      designation: "貿易・投資参事官",
      tel: "(03)-5421-7741 (内線 #46 & #36))",
      fax: "(03)-5421-3613",
      image: "/assets/img/others/about_me.png",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "アーシジ・ルクマン・ハフィズ",
      designation: "コミュニティ福祉駐在官",
      tel: "(03)-5421-7741 (内線 #21 & #31)",
      fax: "(03)-5421-3610",
      image: "/assets/img/keyPerson/ashij.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    {
      name: "ムハンマド・ナヴィード・シャヘザード",
      designation: "機械読み取り可能なパスポートの責任者",
      tel: "(03)-5421-7742 (内線 #13)",
      fax: "(03)-5421-3610",
      image: "/assets/img/keyPerson/naveed.jpg",
      social: [
        { platform: "facebook", url: "#", iconClass: "fab fa-facebook-f" },
        { platform: "twitter", url: "#", iconClass: "fab fa-twitter" },
        { platform: "behance", url: "#", iconClass: "fab fa-behance" },
        { platform: "youtube", url: "#", iconClass: "fab fa-youtube" },
      ],
    },
    // Add more objects for additional people
  ];
  